# Generated by Django 4.0.4 on 2022-05-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='user_id',
            new_name='user',
        ),
    ]
