# Generated by Django 4.0.4 on 2022-05-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0004_rename_game_id_rating_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='gamer_id',
            new_name='gamer',
        ),
    ]
