# Generated by Django 4.0.4 on 2022-05-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0005_rename_game_id_image_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamer_id',
            new_name='gamer',
        ),
    ]
